### ISSUE TITLE
Same color for comments and selected text background

### ISSUE THREAD

**Issue by ghost** [Angular-io-Code/Angular-io-Code#1]
Hello. Thank you for your work, the theme is beautiful.
However there is an issue ; the color for comments and the color for selected text background is the same color (a dark grey shade). This results in the impossibility to read comments into a selected text area.
J.

**Comment by NoHomey** [comment]
I've changed to color to #FFECEC I think overall it's way better now not just for comments. See if you like it and if you do I'll close the issue.

**Comment by ghost** [comment]
Great, it's working just fine. Thank you !
